AWSTemplateFormatVersion: '2010-09-09'
Description: EC2test

Resources:
  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpc
      CidrBlock: 10.0.1.0/24
  
  securityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      VpcId: !Ref vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80          
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-088b486f20fab3f0e
      InstanceType: t3.micro
      KeyName: aws-test
      SecurityGroupIds:
        - !Ref securityGroup
      SubnetId: !Ref subnet
      Tags:
        - Key: Name
          Value: MyEC2Instance

